languageCode: 'en-us'
theme: 'hello-friend'
paginate: 3
hideReadMore: true
hasCJKLanguage: true

baseURL: 'https://tgc54.com'


languages:
  en:
    title: "Thallium54"
    menu:
      main:
        - identifier: "posts"
          name: "Posts"
          url: "/posts"
          weight: 1
        - identifier: "categories"
          name: "Categories"
          url: "/categories"
          weight: 2
        - identifier: "Tags"
          name: "Tags"
          url: "/tags"
          weight: 3
        - identifier: "Wiki"
          name: "Wiki"
          url: "https://wiki.tgc54.com"
          weight: 4
    params:
      logo:
        logoText: Thallium54
        logoHomeLink: '/'
      langName: English
      showMenuItems: 2
  zh:
    title: "Thallium54"
    contentDir: content/zh
    menu:
      main:
        - identifier: "posts"
          name: "博文"
          url: "/zh/posts"
          weight: 1
        - identifier: "Categories"
          name: "分类"
          url: "/zh/categories"
          weight: 2
        - identifier: "tags"
          name: "标签"
          url: "/zh/tags"
          weight: 3
        - identifier: "Wiki"
          name: "Wiki"
          url: "https://wiki.tgc54.com"
          weight: 4
    params:
      logo:
        logoText: Thallium54
        logoHomeLink: '/zh'
      langName: 简体中文
